### ISSUE TITLE
Вынести из CurrencyDAO работу с ExchangeRate

### ISSUE THREAD

**Issue by ibobrov** [WillSalas2002/currency-exchange-api#4]
- [x] Переименнуй в findAll()
https://github.com/WillSalas2002/currency-exchange-api/blob/7cff3f55d7de50c97758d11b6428dc51beb84fae/src/main/java/currency_exchange_api/dao/CurrencyDAOImpl.java#L15

- [x] findByCode
https://github.com/WillSalas2002/currency-exchange-api/blob/7cff3f55d7de50c97758d11b6428dc51beb84fae/src/main/java/currency_exchange_api/dao/CurrencyDAOImpl.java#L32

- [x] Выноси в ExcangeRateDAO и там этот метод тоже findAll()
https://github.com/WillSalas2002/currency-exchange-api/blob/7cff3f55d7de50c97758d11b6428dc51beb84fae/src/main/java/currency_exchange_api/dao/CurrencyDAOImpl.java#L53

- [x] В ExcangeRateDAO и там этот метод findByCurrencyCode(String baseCode, String targetCode)
https://github.com/WillSalas2002/currency-exchange-api/blob/7cff3f55d7de50c97758d11b6428dc51beb84fae/src/main/java/currency_exchange_api/dao/CurrencyDAOImpl.java#L71

- [x] Переделывай в save(Currency currency)
https://github.com/WillSalas2002/currency-exchange-api/blob/7cff3f55d7de50c97758d11b6428dc51beb84fae/src/main/java/currency_exchange_api/dao/CurrencyDAOImpl.java#L94

- [x] В отдельном классе с рейтом, по тому же принцепу save(ExcangeRate exchangeRate)
https://github.com/WillSalas2002/currency-exchange-api/blob/7cff3f55d7de50c97758d11b6428dc51beb84fae/src/main/java/currency_exchange_api/dao/CurrencyDAOImpl.java#L110

- [x] В отдельном классе, update(int id, ExchangeRate exchangeRate)
https://github.com/WillSalas2002/currency-exchange-api/blob/7cff3f55d7de50c97758d11b6428dc51beb84fae/src/main/java/currency_exchange_api/dao/CurrencyDAOImpl.java#L136

- [x] findById(int id)
https://github.com/WillSalas2002/currency-exchange-api/blob/7cff3f55d7de50c97758d11b6428dc51beb84fae/src/main/java/currency_exchange_api/dao/CurrencyDAOImpl.java#L150

- [x] называешь оба to... заместо get... и второй выносишь в отдельный класс для ExcangeRate
https://github.com/WillSalas2002/currency-exchange-api/blob/7cff3f55d7de50c97758d11b6428dc51beb84fae/src/main/java/currency_exchange_api/dao/CurrencyDAOImpl.java#L165-L174

- [x] Ниже обязательно оставь ссылку коммит.

**Comment by WillSalas2002** [comment]
https://github.com/WillSalas2002/currency-exchange-api/commit/1e291a04c869940262de9d49b6d857293947669d

**Comment by ibobrov** [comment]
Ок, хорошо
