### ISSUE TITLE
Добавить checkstyle и убрать пыстые строки

### ISSUE THREAD

**Issue by ibobrov** [WillSalas2002/currency-exchange-api#5]
- [x] checkstyle файл такой
https://github.com/ibobrov/test/blob/master/checkstyle.xml

- [x] в pom прописать вот так
https://github.com/ibobrov/test/blob/c0f0888a0d8ab8a51647fbfcda891c8c6acb06cb/pom.xml#L89C13-L116

- [x] в maven запустить на в кладке справа, validate

**Comment by ibobrov** [comment]
Ниже коммит обязательно.

**Comment by WillSalas2002** [comment]
https://github.com/WillSalas2002/currency-exchange-api/commit/e834e99556286bc1e452cf03c75aaf41a25333b7

**Comment by ibobrov** [comment]
Хорошо, молодец
